### ISSUE TITLE
Can't turn folder into anb

### ISSUE THREAD

**Issue by DoctorSmol123** [leamsii/Shovel-Knight-Packer#13]
When I try to drag and drop the folder onto the anb tool, nothing happens so I tried to do it through CMD and got this:

Log: Packing 67 Animation(s)..
The system cannot find the path specified.
Traceback (most recent call last):
  File "anb_tool.py", line 16, in <module>
    ANBPack(filename)
  File "include\anb_pack.py", line 77, in __init__
  File "include\anb_pack.py", line 204, in compress_image
struct.error: unpack requires a buffer of 4 bytes

**Comment by leamsii** [comment]
Looks like you might have an invalid file in your folder. Send me a screenshot of the files

**Comment by DoctorSmol123** [comment]
Thank you for the reply! I assume you drag and drop plaguePlayer onto anb
tool correct?

**Comment by swipht666** [comment]
I can't extract .anb files using .anb tools

**Comment by DoctorSmol123** [comment]
Ah I see, thank you for replying it’s been a few years LOL
